### PR TITLE
add JSON import, fix #2

### LINKED ISSUE #2: Opening Theme
Currently if I want to edit a theme that I have previously exported after closing the app I need to modify the code and recompile to load the theme in, this is fine but it would great if it were possible to load a theme into the app - apologies if this function already exists and I have missed it. Also loading a path could give a warning that it will immediately overwrite a file rather than open it.

### PR DESCRIPTION
**Pull request by edvorg**
hello, again :) I have added a simple JSON import that should fix #2 

screenshot:

image

### CODE REVIEW

**Comment by edvorg** [comment]
@grantshandy one current downside is that there is no visual feedback on malformed input or successful import. I had some success with using this library https://github.com/ItsEthra/egui-notify

If you approve, I could update the PR to show some neat status popups

toasts_example_video

**Comment by edvorg** [comment]
@grantshandy  Oh, somehow I missed that you actually are already using this library. So I updated the pull request to use it as well in the import section.

**Comment by edvorg** [comment]
image
image

**Comment by grantshandy** [comment]
Thanks! I was actually working on this last night before I went to bed, but hit the file loading/`Style` update synchronization thing and decided to sleep because I realized I would have to refactor the `Toasts` and add an update channel 😅.

**Comment by edvorg** [comment]
@grantshandy  Haha, glad I could help out a bit :)

**Pull request merged**
